"""Assemble the supply-chain chart pack PDF from the current generated figures.

One page per chart: title, a short factual caption (claims match the docs --
measured statements only), and the figure. Sections:
  1  The chain as flows        (exports/: overviews, network, stage hub charts)
  2  The time-varying factor model  (results/mfm/tvmfm/: drift, loadings, factors)
  3  Concentration & fragmentation  (results/network_stats/)

Every figure is produced by the scripts noted on its page; rerun those first if
data changed. Output: exports/chart_pack.pdf (committed).

`python scripts/build_chart_pack.py mobile` writes chart_pack_mobile.pdf
instead: phone-width portrait pages (one chart per page, page height sized to
the chart, larger type) for reading on a phone without pinching.
"""
from __future__ import annotations
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.backends.backend_pdf import PdfPages

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from gec import config as cfg

EX = cfg.ROOT / "exports"
TV = cfg.RESULTS_DIR / "mfm" / "tvmfm"
NS = cfg.RESULTS_DIR / "network_stats"
OUT = EX / "chart_pack.pdf"

SECTIONS = [
 ("1. The chain as flows",
  "2024 bilateral flows, China+Hong Kong merged (CHK), intra-bloc excluded. "
  "Stages 1-5 from Atlas HS2012 annual data; stages 6-8 from the monthly panel "
  "(docs/data.md §3). Generated by scripts/export_supply_chain_sankey.py.",
  [
   (EX/"overviews/supply_chain_overview_dollar_coarse_2024.png",
    "Whole-chain overview, dollar scale (coarse)",
    "All eight stages left to right; band width = 2024 dollars. Inputs, litho "
    "optics and equipment run in parallel and converge on the fab countries; "
    "parts and baseboards form the intra-assembly segment before servers."),
   (EX/"overviews/supply_chain_overview_normalized_coarse_2024.png",
    "Whole-chain overview, normalized (coarse)",
    "Same flows with each stage rescaled to equal width, so small stages' "
    "composition is readable (dollar scale makes chips dwarf everything)."),
   (EX/"network/supply_chain_network_2024.png",
    "Country network, all stages",
    "Nodes = countries, edges = 2024 flows colored by stage. Shows integrated "
    "roles a stage sequence cannot: Mexico takes in chips and parts and ships "
    "out servers at a single node."),
   (EX/"hubs_nnf/supply_chain_1_raw_materials_nnf_hubs_2024.png",
    "Stage 1 -- raw materials, hub decomposition",
    "Four-column view: exporters -> export hubs -> import hubs -> importers, "
    "hubs estimated by MFM in the nonnegativity-identified basis. Applies to "
    "every stage page that follows; fits R² 0.95-0.99."),
   (EX/"hubs_nnf/supply_chain_2_wafers_nnf_hubs_2024.png",
    "Stage 2 -- wafers & wafer inputs", ""),
   (EX/"hubs_nnf/supply_chain_3_litho_optics_nnf_hubs_2024.png",
    "Stage 3 -- lithography & optics inputs", ""),
   (EX/"hubs_nnf/supply_chain_4_equipment_nnf_hubs_2024.png",
    "Stage 4 -- fab equipment",
    "Capacity goods, not consumables: in fab countries these imports lead chip "
    "exports by 6-12 months (docs/notes/edge-type-tests.md)."),
   (EX/"hubs_nnf/supply_chain_5_chips_nnf_hubs_2024.png",
    "Stage 5 -- chips (logic, memory, discretes)", ""),
   (EX/"hubs_nnf/supply_chain_6_parts_nnf_hubs_2024.png",
    "Stage 6 -- parts & GPU modules (847330)", ""),
   (EX/"hubs_nnf/supply_chain_7_baseboards_nnf_hubs_2024.png",
    "Stage 7 -- baseboards (847180)", ""),
   (EX/"hubs_nnf/supply_chain_8_servers_nnf_hubs_2024.png",
    "Stage 8 -- AI servers (847150)", ""),
  ]),
 ("2. The time-varying factor model",
  "Era-anchored TV-MFM on the audited monthly panel (12m trailing window, "
  "k=4, $B levels, NNF basis), 2017-12..2026-04. Shaded bands = eras between "
  "structural breaks. Generated by scripts/tvmfm_monthly_anchored.py; "
  "summaries in results/mfm/tvmfm/.",
  [
   (TV/"chn_hkg_bloc/ai_compute/drift.png",
    "AI compute, CHK basis -- loading drift and eras",
    "The preferred basis (entrepot churn netted; Taiwan separate). One "
    "unbroken 68-month era from 2017-12, then breaks at 2023-08, 2024-10, "
    "2025-09."),
   (TV/"chn_hkg_bloc/ai_compute/loadings_export.png",
    "AI compute, CHK basis -- export-hub loadings",
    "Per-hub country loadings through time. At 2024-10 the China-bloc hub "
    "loses its separate identity (cross-era similarity 0.45) and a "
    "Singapore-led hub appears."),
   (TV/"chn_hkg_bloc/ai_compute/loadings_import.png",
    "AI compute, CHK basis -- import-hub loadings",
    "Import hubs are the stable side of the network (USA, Mexico, Taiwan, "
    "rest-of-world led)."),
   (TV/"chn_hkg_bloc/ai_compute/factors.png",
    "AI compute, CHK basis -- hub-to-hub intensities F_t",
    "Each panel is one export-hub x import-hub channel in $B (3m MA thick)."),
   (TV/"by_country/ai_compute/drift.png",
    "AI compute, country level -- drift",
    "Without bloc merging the sample splits once: 2023-08. The demand event "
    "is the only dominant country-level break in nine years."),
   (TV/"by_country/847330/drift.png",
    "Parts (847330), country level -- drift",
    "91 months without a structural break; the parts layer is the stable "
    "substrate of the network."),
   (TV/"chnhkg_usamex_blocs/ai_compute/drift.png",
    "AI compute, double-bloc basis -- drift",
    "CHK and USA+MEX both merged, isolating cross-bloc structure. Breaks at "
    "2019-04/2019-12 (first tariff war), 2022-10 (first export controls), "
    "2025-04 (tariffs): policy breaks blocs."),
   (TV/"chnhkg_usamex_blocs/ai_compute/loadings_export.png",
    "AI compute, double-bloc basis -- export-hub loadings",
    "In the 2025-04 era the two blocs load together on one factor (CHK +3.97, "
    "USM +3.41) -- the entanglement signature unique to the tariff break."),
  ]),
 ("3. Concentration & fragmentation",
  "Measure system of docs/concentration-fragmentation-nnf-mfm-trade.md "
  "computed monthly from the TV-MFM (CHK basis). Dotted lines mark 2023-07 "
  "and 2025-04. Interpretation: results/network_stats/findings.md. Generated "
  "by scripts/network_stats.py.",
  [
   (NS/"ai_compute/fragmentation.png",
    "Two notions of fragmentation -- AI compute",
    "Left: hub-overlap fragmentation (range-compressed under the anchored "
    "basis; mainly a diagnostic). Right: bloc channel shares -- the "
    "cross-bloc CN-US share falls ~70% over the sample in two legs (2019, "
    "then 2023 onward) with a plateau between."),
   (NS/"ai_compute/decomposition.png",
    "Joint concentration decomposition -- AI compute",
    "HHI_flat = HHI_F x (mu_a mu_b + alignment covariance), exact identity. "
    "Alignment covariance is mildly positive from 2017, peaks ~2019, decays "
    "through the AI era: no compounding-concentration signature."),
   (NS/"ai_compute/linkage.png",
    "Per-hub linkage concentration and basis diagnostic -- AI compute",
    "Left: does an export hub sell into one import program or several. "
    "Right: clipped negative mass (basis quality), elevated during the "
    "2023-24 regime transition."),
   (NS/"847180/fragmentation.png",
    "Fragmentation -- baseboards (847180)",
    "The sharpest decoupling of the three codes: the cross-bloc share "
    "collapses ~20x from its 2021 peak while linkage concentration HHI_F "
    "rises 0.09 -> 0.48."),
   (NS/"847330/fragmentation.png",
    "Fragmentation -- parts (847330)",
    "Cross-bloc share halves but remains the highest of the three codes: "
    "the parts layer stays the shared substrate."),
  ]),
]


def _wrap(text, width):
    import textwrap
    return "\n".join(textwrap.wrap(text, width)) if text else ""


def page(pdf, img_path, title, caption, section):
    fig = plt.figure(figsize=(11.69, 8.27))
    fig.text(0.06, 0.955, title, fontsize=15, weight="bold", va="top")
    fig.text(0.94, 0.955, section, fontsize=8, color="#888", va="top", ha="right")
    if caption:
        fig.text(0.06, 0.915, caption, fontsize=9, va="top", wrap=True,
                 color="#333", family="sans-serif")
    img = mpimg.imread(img_path)
    top = 0.83 if caption else 0.90
    ax = fig.add_axes([0.03, 0.02, 0.94, top - 0.02])
    ax.imshow(img)
    ax.axis("off")
    pdf.savefig(fig)
    plt.close(fig)


def divider(pdf, title, blurb):
    fig = plt.figure(figsize=(11.69, 8.27))
    fig.text(0.5, 0.58, title, fontsize=26, weight="bold", ha="center")
    fig.text(0.5, 0.48, blurb, fontsize=11, ha="center", wrap=True, color="#333")
    pdf.savefig(fig)
    plt.close(fig)


W = 6.0  # phone page width, inches


def page_mobile(pdf, img_path, title, caption, section):
    t = _wrap(title, 44)
    c = _wrap(caption, 62)
    img = mpimg.imread(img_path)
    img_h = W * img.shape[0] / img.shape[1]
    head = 0.52 + 0.24 * t.count("\n") + (0.16 * (c.count("\n") + 1) + 0.12 if c else 0.06)
    fig = plt.figure(figsize=(W, head + img_h + 0.15))
    H = fig.get_figheight()
    fig.text(0.04, 1 - 0.10 / H, section, fontsize=7.5, color="#888", va="top")
    fig.text(0.04, 1 - 0.24 / H, t, fontsize=13, weight="bold", va="top")
    if c:
        fig.text(0.04, 1 - (0.46 + 0.24 * t.count("\n")) / H, c, fontsize=9.5,
                 va="top", color="#333")
    ax = fig.add_axes([0.0, 0.10 / H, 1.0, img_h / H])
    ax.imshow(img)
    ax.axis("off")
    pdf.savefig(fig)
    plt.close(fig)


def divider_mobile(pdf, title, blurb):
    b = _wrap(blurb, 58)
    fig = plt.figure(figsize=(W, 3.2))
    fig.text(0.5, 0.72, title, fontsize=18, weight="bold", ha="center")
    fig.text(0.5, 0.58, b, fontsize=9.5, ha="center", va="top", color="#333")
    pdf.savefig(fig)
    plt.close(fig)


def main(mobile=False):
    missing = [str(p) for _, _, items in SECTIONS for p, _, _ in items
               if not p.exists()]
    if missing:
        sys.exit("missing figures (regenerate first):\n" + "\n".join(missing))
    import datetime
    out = EX / ("chart_pack_mobile.pdf" if mobile else "chart_pack.pdf")
    intro = ("Current state of the analysis. Data: UN Comtrade + TDM monthly "
             "panel (60 HS6 codes, 2017-01..2026-04, audited vs Atlas) and "
             "Atlas HS2012 annual. Sections: 1 the chain as flows (2024) -- "
             "2 the time-varying factor model -- 3 concentration & "
             "fragmentation. Details: docs/data.md, "
             "docs/supply-chain-narrative.md, results/.")
    with PdfPages(out) as pdf:
        if mobile:
            fig = plt.figure(figsize=(W, 4.6))
            fig.text(0.5, 0.80, _wrap("AI-compute supply chain: chart pack", 26),
                     fontsize=20, weight="bold", ha="center", va="top")
            fig.text(0.5, 0.55, _wrap(intro, 58), fontsize=9.5, ha="center",
                     va="top", color="#333")
            fig.text(0.5, 0.08, datetime.date.today().isoformat(),
                     fontsize=9, ha="center", color="#888")
            pdf.savefig(fig)
            plt.close(fig)
            for title, blurb, items in SECTIONS:
                divider_mobile(pdf, title, blurb)
                for p, t, c in items:
                    page_mobile(pdf, p, t, c, title)
        else:
            fig = plt.figure(figsize=(11.69, 8.27))
            fig.text(0.5, 0.62, "AI-compute supply chain: chart pack",
                     fontsize=28, weight="bold", ha="center")
            fig.text(0.5, 0.52, intro.replace(" Sections:", "\nSections:")
                     .replace(" Details:", "\nDetails:"),
                     fontsize=11, ha="center", color="#333")
            fig.text(0.5, 0.40, datetime.date.today().isoformat(),
                     fontsize=10, ha="center", color="#888")
            pdf.savefig(fig)
            plt.close(fig)
            for title, blurb, items in SECTIONS:
                divider(pdf, title, blurb)
                for p, t, c in items:
                    page(pdf, p, t, c, title)
    n = 1 + sum(1 + len(items) for _, _, items in SECTIONS)
    print(f"{out} written: {n} pages")


if __name__ == "__main__":
    main(mobile="mobile" in sys.argv[1:])
